### ISSUE TITLE
NO WINDOWS SUPPORT???

### ISSUE THREAD

**Issue by KumarAbhirup** [KumarAbhirup/bulk-mail-cli#14]
Why the hell does `bulk-mail-cli` revoke its support for Windows machines???

**Comment by KumarAbhirup** [comment]
**bulk-mail-cli is not tested on Windows.** Morever, The terminal text formatting might break there. Windows has some different file system which might break common paths. 

Will add Windows support sooner or later after the linux build is built.

**Comment by Suleman-Elahi** [comment]
![image](https://user-images.githubusercontent.com/24384996/49848285-77e5cb80-fdfa-11e8-90c1-c0830a71668d.png)

**Comment by KumarAbhirup** [comment]
Hey, right now, `bulk-mail-cli` doesn't support Windows machines. I will update the package by tomorrow. 👍

**Comment by KumarAbhirup** [comment]
*UPDATE:* I haven't made many updates yet. bulk-mail-cli is still underdeveloped, even on linux. Will improve that first, and then comes WIndows support 👍

**Comment by KumarAbhirup** [comment]
Working on this issue. So far, created a version that works on Windows, but has severe performance issues.

**Comment by KumarAbhirup** [comment]
bulk-mail-cli `v1.0.2` now supports Windows OS. Test the program hard.
There might be bugs. If you find any, report them.
