### ISSUE TITLE
Wanna sell the Project?

### ISSUE THREAD

**Issue by OliverWeise-Omnis** [KumarAbhirup/bulk-mail-cli#18]
Why do you want to sell this community project? You earn the money for the work of others?
https://1kprojects.com/project/bulk-mail-cli

**Comment by KumarAbhirup** [comment]
Nopes, what are you saying?? Can you explain??

**Comment by KumarAbhirup** [comment]
I think I should. 💯 

I see I just can't delete the project from 1kProjects. I see no such option.
You can do it from your side though. :-)
