### ISSUE TITLE
feat: Front-end

### ISSUE THREAD

**Issue by ghost** [KumarAbhirup/bulk-mail-cli#29]
It'd be great if non-IT users could have some kind of back office to send their mails:

- A button to import a CSV that contains a batch of mails
- An editor where the mails would go and could easily be edited
- An editor where the mail template would go
- Some settings button to set up CRON etc.
- Notifications

If you set up some kind of web socket that would be pretty easy for the front-end to follow ?

**Comment by kumarabhirup** [comment]
You might not believe it, but what you asked for is already under construction 🤪

It won't rely on bulk-mail-cli though, it is a completely new project but with the fundamentals of bulk-mail-cli, combined with Email, WhatsApp, Telegram and Twitter.

It is planned to be launched in January.

**Comment by ghost** [comment]
Good news for my non IT staff I'll be looking forward to it!

**Comment by kumarabhirup** [comment]
Sure! You would love it!

**Comment by kumarabhirup** [comment]
https://propagate.at

@thoughtsunificator  keep an eye on it 😉

**Comment by kumarabhirup** [comment]
Never mind, that project has evolved into something very different now.
