### ISSUE TITLE
GDPR and Privacy

### ISSUE THREAD

**Issue by AndreaMonzini** [KumarAbhirup/bulk-mail-cli#30]
Hello!
thank you for the interesting project!

Are the  Privacy  and the GDPR rules mainteined in the command line process?

thank you

**Comment by kumarabhirup** [comment]
Yes.

The Command-Line App DOES NOT store any information on any servers. 

The app is completely based on your machine/server and the data also stays on your machine only (in the form of a JSON file that you can access anytime in your folder structure).

If you have any more questions, feel free to ask :)
