### ISSUE TITLE
Make Ctrl+C work for every processes

### ISSUE THREAD

**Issue by kumarabhirup** [KumarAbhirup/bulk-mail-cli#8]
Everytime an input process starts, it simply doesn't cancel by Ctrl+C. Thus, leading to frustration and to completely quit the terminal and start from scratch. **Urgent!**

**Comment by KumarAbhirup** [comment]
This issue could make sense here. So adding... [Terminal Kit issue #24](https://github.com/cronvel/terminal-kit/issues/24)

We need to implement same block of code.
